"""Create a migration branch and open a Pull Request via git + gh."""

from __future__ import annotations

import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from conduit.patcher.engine import PatchReport
from conduit.test_runner import TestResult


@dataclass
class PRResult:
    branch: str
    title: str
    url: str | None
    created: bool
    message: str


def _run(cmd: list[str], cwd: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        cmd,
        cwd=cwd,
        capture_output=True,
        text=True,
        check=False,
    )


def build_pr_body(
    packet: dict[str, Any],
    report: PatchReport,
    test_result: TestResult,
    *,
    detect_summary: str = "",
) -> str:
    package = packet.get("package", "package")
    from_v = packet.get("from_version", "?")
    to_v = packet.get("to_version", "?")
    packet_id = packet.get("packet_id", "")
    sources = packet.get("sources") or []
    source = sources[0]["url"] if sources else "n/a"

    change_lines = [f"- {c.detail} in `{c.path}`" for c in report.changes] or [
        "- (no file-level change details recorded)"
    ]
    status = "Passed" if test_result.passed else "Failed"
    detect_block = f"\n### Detect\n{detect_summary}\n" if detect_summary else "\n"

    return f"""## Conduit migration

**Package:** `{package}` `{from_v}` → `{to_v}`
**Packet:** `{packet_id}`
{detect_block}
### Changes applied
{chr(10).join(change_lines)}

### Verification
- Tests: {status}
- Command: `{' '.join(test_result.command) or 'n/a'}`
- Source: {source}

---
*Generated by Conduit*
"""


def build_pr_title(packet: dict[str, Any]) -> str:
    package = packet.get("package", "package")
    to_v = packet.get("to_version", "new")
    return f"[Conduit] Upgrade {package} to {to_v}"


def open_pull_request(
    root: Path,
    packet: dict[str, Any],
    report: PatchReport,
    test_result: TestResult,
    *,
    push: bool = True,
    create_pr: bool = True,
    detect_summary: str = "",
) -> PRResult:
    package = str(packet.get("package", "package"))
    to_v = str(packet.get("to_version", "version")).replace("/", "-")
    branch = f"conduit/upgrade-{package}-{to_v}"
    title = build_pr_title(packet)
    body = build_pr_body(
        packet, report, test_result, detect_summary=detect_summary
    )

    if _run(["git", "rev-parse", "--is-inside-work-tree"], root).returncode != 0:
        return PRResult(
            branch=branch,
            title=title,
            url=None,
            created=False,
            message="Not a git repository; skipped PR creation.",
        )

    _run(["git", "checkout", "-B", branch], root)
    if report.files_modified:
        _run(["git", "add", "--"] + report.files_modified, root)
    else:
        _run(["git", "add", "-A"], root)

    commit = _run(["git", "commit", "-m", title], root)
    if commit.returncode != 0 and "nothing to commit" not in (
        commit.stdout + commit.stderr
    ):
        pass

    if push:
        push_proc = _run(["git", "push", "-u", "origin", "HEAD"], root)
        if push_proc.returncode != 0:
            return PRResult(
                branch=branch,
                title=title,
                url=None,
                created=False,
                message=f"Push failed: {push_proc.stderr.strip() or push_proc.stdout.strip()}",
            )

    if not create_pr:
        return PRResult(
            branch=branch,
            title=title,
            url=None,
            created=True,
            message=f"Branch {branch} ready (PR creation skipped).",
        )

    pr = _run(
        ["gh", "pr", "create", "--title", title, "--body", body, "--head", branch],
        root,
    )
    if pr.returncode != 0:
        return PRResult(
            branch=branch,
            title=title,
            url=None,
            created=False,
            message=f"gh pr create failed: {pr.stderr.strip() or pr.stdout.strip()}",
        )

    url = (pr.stdout or "").strip().splitlines()[-1] if pr.stdout else None
    return PRResult(
        branch=branch,
        title=title,
        url=url,
        created=True,
        message=f"Opened PR: {url}",
    )
