"""Generate a minimal smoke test suite when the consumer repo has none."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from conduit.llm import get_llm_client
from conduit.test_runner import detect_test_command


def _has_test_files(root: Path) -> bool:
    if (root / "tests").is_dir() and any((root / "tests").rglob("test_*.py")):
        return True
    if any(root.glob("test_*.py")):
        return True
    if any(root.rglob("*.test.js")) or any(root.rglob("*.test.ts")):
        return True
    if any(root.rglob("*.spec.js")) or any(root.rglob("*.spec.ts")):
        return True
    return False


def ensure_tests(
    root: Path,
    packet: dict[str, Any],
    *,
    changed_files: list[str] | None = None,
) -> list[str]:
    """
    If no native test suite / test files exist, create a smoke test.
    Returns list of created relative paths.
    """
    root = root.resolve()
    detected = detect_test_command(root)
    if detected is not None and _has_test_files(root):
        return []

    ecosystem = packet.get("ecosystem") or "pypi"
    package = packet.get("package") or "unknown"

    # Prefer LLM generation when configured
    client = get_llm_client()
    if client is not None:
        created = _llm_generate_tests(
            root, packet, changed_files=changed_files or [], ecosystem=ecosystem
        )
        if created:
            return created

    if ecosystem == "npm":
        return [_write_js_stub(root, package, packet)]
    return [_write_pytest_stub(root, package, packet)]


def _write_pytest_stub(root: Path, package: str, packet: dict[str, Any]) -> str:
    tests = root / "tests"
    tests.mkdir(parents=True, exist_ok=True)
    path = tests / "test_conduit_migration.py"
    from_v = packet.get("from_version", "?")
    to_v = packet.get("to_version", "?")
    content = f'''"""Auto-generated by Conduit — smoke test for {package} {from_v} -> {to_v}."""

from __future__ import annotations


def test_package_importable():
    """Ensure the migrated dependency still imports."""
    mod = __import__({package!r})
    assert mod is not None


def test_migration_packet_applied():
    """Placeholder assertion documenting the Conduit migration."""
    assert {from_v!r} != {to_v!r} or True
'''
    path.write_text(content, encoding="utf-8")
    return str(path.relative_to(root))


def _write_js_stub(root: Path, package: str, packet: dict[str, Any]) -> str:
    path = root / "conduit_migration.test.js"
    from_v = packet.get("from_version", "?")
    to_v = packet.get("to_version", "?")
    content = f"""/** Auto-generated by Conduit — smoke test for {package} {from_v} -> {to_v} */
test('migration marker', () => {{
  expect('{from_v}' !== '{to_v}' || true).toBe(true);
}});
"""
    path.write_text(content, encoding="utf-8")
    return str(path.relative_to(root))


def _llm_generate_tests(
    root: Path,
    packet: dict[str, Any],
    *,
    changed_files: list[str],
    ecosystem: str,
) -> list[str]:
    client = get_llm_client()
    if client is None:
        return []

    samples: dict[str, str] = {}
    for rel in changed_files[:8]:
        path = root / rel
        if path.is_file():
            try:
                samples[rel] = path.read_text(encoding="utf-8")[:4000]
            except OSError:
                continue

    prompt = {
        "instructions": (
            "Generate a minimal smoke test for a repo after an API migration. "
            'Return JSON: {"files": {"relative/path": "full file contents"}}. '
            "For Python use tests/test_conduit_migration.py with pytest. "
            "For npm use a *.test.js file. Do not require network calls."
        ),
        "ecosystem": ecosystem,
        "packet": {
            "package": packet.get("package"),
            "from_version": packet.get("from_version"),
            "to_version": packet.get("to_version"),
            "rules": packet.get("rules") or [],
        },
        "changed_files": samples,
    }
    try:
        data = client.complete_json(
            system="You write minimal migration smoke tests. JSON only.",
            user=json.dumps(prompt),
        )
    except Exception:
        return []

    files = data.get("files") or {}
    created: list[str] = []
    root_resolved = root.resolve()
    for rel, content in files.items():
        if not isinstance(content, str):
            continue
        path = (root / str(rel)).resolve()
        if not str(path).startswith(str(root_resolved)):
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        created.append(str(rel))
    return created
