"""Create a migration branch and open a Pull Request via git + gh."""

from __future__ import annotations

import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from vendor_patch_cli.patcher.engine import PatchReport
from vendor_patch_cli.test_runner import TestResult


@dataclass
class PRResult:
    branch: str
    title: str
    url: str | None
    created: bool
    message: str


def _run(cmd: list[str], cwd: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        cmd,
        cwd=cwd,
        capture_output=True,
        text=True,
        check=False,
    )


def _vendor_title(vendor: str) -> str:
    return vendor[:1].upper() + vendor[1:] if vendor else "Vendor"


def build_pr_body(
    events: list[dict[str, Any]],
    report: PatchReport,
    test_result: TestResult,
) -> str:
    primary = events[0] if events else {}
    vendor = _vendor_title(str(primary.get("vendor", "unknown")))
    affected = primary.get("affected_pattern", "?")
    replacement = primary.get("replacement_pattern", "?")
    deadline = (primary.get("deadline") or "unknown")[:10]
    source = primary.get("source_url") or "https://platform.openai.com/docs/deprecations"

    change_lines = []
    for change in report.changes:
        change_lines.append(f"- {change.detail} in `{change.path}`")
    if not change_lines:
        change_lines.append("- (no file-level change details recorded)")

    status = "Passed" if test_result.passed else "Failed"
    body = f"""## Automatic API Patch
**Vendor:** {vendor}
**Upstream Change:** Pattern `{affected}` migrating to `{replacement}` (deadline **{deadline}**).

### Changes Applied:
{chr(10).join(change_lines)}

### Verification:
- Unit Tests Executed: {status}
- Command: `{' '.join(test_result.command) or 'n/a'}`
- Upstream Documentation: [{source}]({source})

---
*Generated by vendor-patch-cli*
"""
    return body


def build_pr_title(events: list[dict[str, Any]]) -> str:
    primary = events[0] if events else {}
    vendor = _vendor_title(str(primary.get("vendor", "vendor")))
    affected = primary.get("affected_pattern", "pattern")
    replacement = primary.get("replacement_pattern", "replacement")
    return f'[Auto-Fix] Migrate deprecated {vendor} "{affected}" -> "{replacement}"'


def open_pull_request(
    root: Path,
    events: list[dict[str, Any]],
    report: PatchReport,
    test_result: TestResult,
    *,
    push: bool = True,
    create_pr: bool = True,
) -> PRResult:
    if not events:
        return PRResult(
            branch="",
            title="",
            url=None,
            created=False,
            message="No events to open a PR for.",
        )

    primary = events[0]
    vendor = str(primary.get("vendor", "vendor"))
    event_id = str(primary.get("event_id", "event"))
    branch = f"auto-fix/{vendor}-migration-{event_id}"
    title = build_pr_title(events)
    body = build_pr_body(events, report, test_result)

    # Ensure we are in a git repo
    if _run(["git", "rev-parse", "--is-inside-work-tree"], root).returncode != 0:
        return PRResult(
            branch=branch,
            title=title,
            url=None,
            created=False,
            message="Not a git repository; skipped PR creation.",
        )

    _run(["git", "checkout", "-B", branch], root)
    if report.files_modified:
        _run(["git", "add", "--"] + report.files_modified, root)
    else:
        _run(["git", "add", "-A"], root)

    commit_msg = title
    commit = _run(["git", "commit", "-m", commit_msg], root)
    if commit.returncode != 0 and "nothing to commit" not in (commit.stdout + commit.stderr):
        # Might already be committed; continue
        pass

    if push:
        push_proc = _run(["git", "push", "-u", "origin", "HEAD"], root)
        if push_proc.returncode != 0:
            return PRResult(
                branch=branch,
                title=title,
                url=None,
                created=False,
                message=f"Push failed: {push_proc.stderr.strip() or push_proc.stdout.strip()}",
            )

    if not create_pr:
        return PRResult(
            branch=branch,
            title=title,
            url=None,
            created=True,
            message=f"Branch {branch} ready (PR creation skipped).",
        )

    pr = _run(
        [
            "gh",
            "pr",
            "create",
            "--title",
            title,
            "--body",
            body,
            "--head",
            branch,
        ],
        root,
    )
    if pr.returncode != 0:
        return PRResult(
            branch=branch,
            title=title,
            url=None,
            created=False,
            message=f"gh pr create failed: {pr.stderr.strip() or pr.stdout.strip()}",
        )

    url = (pr.stdout or "").strip().splitlines()[-1] if pr.stdout else None
    return PRResult(
        branch=branch,
        title=title,
        url=url,
        created=True,
        message=f"Opened PR: {url}",
    )
